ARG target_name
FROM magma/aflgo_mazerunner/${target_name}

## Magma directory hierarchy
# magma_root is relative to the docker-build's working directory
# The Docker image must be built in the root of the magma directory
ARG magma_root=.
ARG magma_path=magma
## Path variables inside the container
ENV MAGMA_R=/magma
ENV SHARED=/magma_shared
ENV MAGMA=${MAGMA_R}/${magma_path}

USER root:root

COPY --chown=magma:magma ${magma_root}/tools/captain/llm_response ${FUZZER}/llm_response
COPY --chown=magma:magma ${magma_root}/fuzzers/llm/preinstall.sh ${FUZZER}
RUN ${FUZZER}/preinstall.sh

USER magma:magma

COPY --chown=magma:magma ${magma_root}/fuzzers/llm/build.sh ${FUZZER}
RUN ${FUZZER}/build.sh

COPY --chown=magma:magma ${magma_root}/fuzzers/llm/run.sh ${FUZZER}
COPY --chown=magma:magma ${magma_root}/fuzzers/llm/runonce.sh ${FUZZER}

ARG GOOGLE_API_KEY
ARG OPENAI_API_KEY
ARG ANTHROPIC_API_KEY
ENV GEMINI_API_KEY=${GOOGLE_API_KEY}
ENV OPENAI_API_KEY=${OPENAI_API_KEY}
ENV ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY}


COPY --chown=magma:magma ${magma_root}/${magma_path}/run.sh ${MAGMA}
COPY --chown=magma:magma ${magma_root}/${magma_path}/runonce.sh ${MAGMA}
COPY --chown=magma:magma ${magma_root}/fuzzers/llm/run.sh ${FUZZER}
COPY --chown=magma:magma ${magma_root}/fuzzers/llm/runonce.sh ${FUZZER}

ENTRYPOINT ["/magma/magma/run.sh"]
